export enum AuthActionType {
    TOGGLE_AUTH = 'TOGGLE_AUTH',
    SET_AUTH = 'SET_AUTH',
}

export enum TopMovieActionType {
    GET_TOP_MOVIES = 'GET_TOP_MOVIES',
    TOGGLE_TOP_MOVIE_WATCHED = 'TOGGLE_TOP_MOVIE_WATCHED',
}

export enum PostsActionType {
    POST_LOADED_SUCCESS = 'POST_LOADED_SUCCESS',
    POST_LOADED_FAIL = 'POST_LOADED_FAIL',
    ADD_POST = 'ADD_POST',
    DELETE_POST = 'DELETE_POST',
    UPDATE_POST = 'UPDATE_POST',
    FIND_POST_BY_ID = 'FIND_POST_BY_ID',
}

export enum NewsActionType {
    NEWS_LOADED_SUCCESS = 'NEWS_LOADED_SUCCESS',
    NEWS_LOADED_MORE_SUCCESS = 'NEWS_LOADED_MORE_SUCCESS',
    NEWS_LOADED_FAIL = 'NEWS_LOADED_FAIL',
    ADD_NEWS = 'ADD_NEWS',
    DELETE_NEWS = 'DELETE_NEWS',
    UPDATE_NEWS = 'UPDATE_NEWS',
    FIND_NEWS_BY_ID = 'FIND_POST_BY_ID',
}

export enum BookActionType {
    BOOK_LOADED_SUCCESS = 'BOOK_LOADED_SUCCESS',
    BOOK_LOADED_MORE_SUCCESS = 'BOOK_LOADED_MORE_SUCCESS',
    BOOK_LOADED_FAIL = 'BOOK_LOADED_FAIL',
    ADD_BOOK = 'ADD_BOOK',
    DELETE_BOOK = 'DELETE_BOOK',
    UPDATE_BOOK = 'UPDATE_BOOK',
    FIND_BOOK_BY_ID = 'FIND_BOOK_BY_ID',
}

export enum ClassficationActionType {
    CLASSIFICATION_LOADED_SUCCESS = 'CLASSIFICATION_LOADED_SUCCESS',
    CLASSIFICATION_LOADED_FAIL = 'CLASSIFICATION_LOADED_FAIL',
}

export enum UserActionType {
    USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS',
    USER_LOADED_MORE_SUCCESS = 'USER_LOADED_MORE_SUCCESS',
    USER_LOADED_FAIL = 'USER_LOADED_FAIL',
    ADD_USER = 'ADD_USER',
    DELETE_USER = 'DELETE_USER',
    UPDATE_USER = 'UPDATE_USER',
    FIND_USER_BY_ID = 'FIND_USER_BY_ID',
}
